apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: http://argocd.naas.local
  oidc.config: |
    name: Authentik
    issuer: http://authentik.naas.local/application/o/argocd/
    clientID: argocd
    clientSecret: $argocd-authentik-secret:oidc.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    groupsClaim: groups
